// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.2.3
// LVGL version: 8.2.0
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI2_H
#define _SQUARELINE_PROJECT_UI2_H

#ifdef __cplusplus
extern "C" {
#endif

#include <lvgl.h>

#include "ui2_events.h"
extern lv_obj_t * ui2_Screen1;
extern lv_obj_t * ui2_Bar2;
extern lv_obj_t * ui2_Bar1;
extern lv_obj_t * ui2____initial_actions0;


LV_IMG_DECLARE(ui2_img_synth_png);    // assets\Synth.png




void ui2_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
