// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.4
// Project name: Right_Display

#include "ui2.h"
#include "ui2_helpers.h"

///////////////////// VARIABLES ////////////////////

// SCREEN: ui2_Screen1
void ui2_Screen1_screen_init(void);
lv_obj_t * ui2_Screen1;
lv_obj_t * ui2_VolTopSlider;
lv_obj_t * ui2_VolBotSlider;

// SCREEN: ui2_Screen2
void ui2_Screen2_screen_init(void);
lv_obj_t * ui2_Screen2;
lv_obj_t * ui2_EQSlider1;
lv_obj_t * ui2_EQSlider2;
lv_obj_t * ui2_EQSlider3;
lv_obj_t * ui2_EQSlider4;
lv_obj_t * ui2_EQSlider5;
lv_obj_t * ui2_EQSlider6;
lv_obj_t * ui2_EQSlider7;
lv_obj_t * ui2_EQSlider8;
lv_obj_t * ui2_EQSlider9;
lv_obj_t * ui2_EQSlider10;
lv_obj_t * ui2_EQSlider11;
lv_obj_t * ui2_EQSlider12;
lv_obj_t * ui2_EQSlider13;
lv_obj_t * ui2_EQSlider14;

// SCREEN: ui2_Screen3
void ui2_Screen3_screen_init(void);
lv_obj_t * ui2_Screen3;
lv_obj_t * ui2_Roller2;
lv_obj_t * ui2_Label1;
lv_obj_t * ui2_Label4;
lv_obj_t * ui2____initial_actions0;

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=1
    #error "LV_COLOR_16_SWAP should be 1 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////

///////////////////// SCREENS ////////////////////

void ui2_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_basic_init(dispp);
    lv_disp_set_theme(dispp, theme);
    ui2_Screen1_screen_init();
    ui2_Screen2_screen_init();
    ui2_Screen3_screen_init();
    ui2____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui2_Screen1);
}
