// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.4
// Project name: Right_Display

#ifndef _RIGHT_DISPLAY_UI2_H
#define _RIGHT_DISPLAY_UI2_H

#ifdef __cplusplus
extern "C" {
#endif

#include <lvgl.h>

#include "ui2_helpers.h"
#include "ui2_events.h"
// SCREEN: ui2_Screen1
void ui2_Screen1_screen_init(void);
extern lv_obj_t * ui2_Screen1;
extern lv_obj_t * ui2_VolTopSlider;
extern lv_obj_t * ui2_VolBotSlider;
// SCREEN: ui2_Screen2
void ui2_Screen2_screen_init(void);
extern lv_obj_t * ui2_Screen2;
extern lv_obj_t * ui2_EQSlider1;
extern lv_obj_t * ui2_EQSlider2;
extern lv_obj_t * ui2_EQSlider3;
extern lv_obj_t * ui2_EQSlider4;
extern lv_obj_t * ui2_EQSlider5;
extern lv_obj_t * ui2_EQSlider6;
extern lv_obj_t * ui2_EQSlider7;
extern lv_obj_t * ui2_EQSlider8;
extern lv_obj_t * ui2_EQSlider9;
extern lv_obj_t * ui2_EQSlider10;
extern lv_obj_t * ui2_EQSlider11;
extern lv_obj_t * ui2_EQSlider12;
extern lv_obj_t * ui2_EQSlider13;
extern lv_obj_t * ui2_EQSlider14;
// SCREEN: ui2_Screen3
void ui2_Screen3_screen_init(void);
extern lv_obj_t * ui2_Screen3;
extern lv_obj_t * ui2_Roller2;
extern lv_obj_t * ui2_Label1;
extern lv_obj_t * ui2_Label4;
extern lv_obj_t * ui2____initial_actions0;

LV_IMG_DECLARE(ui2_img_display_right_vol_bg_png);    // assets\Display_Right_vol_bg.png
LV_IMG_DECLARE(ui2_img_display_right_vol_bar_top_png);    // assets\Display_right_vol_bar_top.png
LV_IMG_DECLARE(ui2_img_display_right_vol_bar_bot_png);    // assets\Display_right_vol_bar_bot.png
LV_IMG_DECLARE(ui2_img_display_right_eq_bg_png);    // assets\Display_Right_eq_bg.png
LV_IMG_DECLARE(ui2_img_display_right_eq_bar_png);    // assets\Display_Right_eq_bar.png
LV_IMG_DECLARE(ui2_img_display_right_vu_bg_png);    // assets\Display_Right_VU_bg.png
LV_FONT_DECLARE(ui_font_Digitaled);

void ui2_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
