// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.2.3
// LVGL version: 8.2.0
// Project name: SquareLine_Project

#include "ui2.h"
#include "ui2_helpers.h"

///////////////////// VARIABLES ////////////////////
lv_obj_t * ui2_Screen1;
lv_obj_t * ui2_Bar2;
lv_obj_t * ui2_Bar1;
lv_obj_t * ui2____initial_actions0;

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////

///////////////////// SCREENS ////////////////////
void ui2_Screen1_screen_init(void)
{
    ui2_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui2_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_img_src(ui2_Screen1, &ui2_img_synth_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui2_Bar2 = lv_bar_create(ui2_Screen1);
    lv_bar_set_value(ui2_Bar2, 25, LV_ANIM_OFF);
    lv_obj_set_width(ui2_Bar2, 224);
    lv_obj_set_height(ui2_Bar2, 25);
    lv_obj_set_align(ui2_Bar2, LV_ALIGN_CENTER);

    ui2_Bar1 = lv_bar_create(ui2_Screen1);
    lv_bar_set_value(ui2_Bar1, 25, LV_ANIM_OFF);
    lv_obj_set_width(ui2_Bar1, 224);
    lv_obj_set_height(ui2_Bar1, 25);
    lv_obj_set_x(ui2_Bar1, 0);
    lv_obj_set_y(ui2_Bar1, -50);
    lv_obj_set_align(ui2_Bar1, LV_ALIGN_CENTER);

}

void ui2_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               true, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui2_Screen1_screen_init();
    ui2____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui2_Screen1);
}
