// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.2.3
// LVGL version: 8.3.4
// Project name: Right_Display

#include "ui2.h"
#include "ui2_helpers.h"

///////////////////// VARIABLES ////////////////////
lv_obj_t * ui2_Screen1;
lv_obj_t * ui2_SliderBottom;
lv_obj_t * ui2_SliderTop;
lv_obj_t * ui2____initial_actions0;

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=1
    #error "LV_COLOR_16_SWAP should be 1 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////

///////////////////// SCREENS ////////////////////
void ui2_Screen1_screen_init(void)
{
    ui2_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui2_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_img_src(ui2_Screen1, &ui2_img_display_off_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui2_SliderBottom = lv_slider_create(ui2_Screen1);
    lv_obj_set_width(ui2_SliderBottom, 320);
    lv_obj_set_height(ui2_SliderBottom, 86);
    lv_obj_set_x(ui2_SliderBottom, 0);
    lv_obj_set_y(ui2_SliderBottom, 42);
    lv_obj_set_align(ui2_SliderBottom, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui2_SliderBottom, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui2_SliderBottom, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui2_SliderBottom, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui2_SliderBottom, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui2_SliderBottom, &ui2_img_display_bot_on_png, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui2_SliderBottom, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui2_SliderBottom, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui2_SliderTop = lv_slider_create(ui2_Screen1);
    lv_obj_set_width(ui2_SliderTop, 320);
    lv_obj_set_height(ui2_SliderTop, 84);
    lv_obj_set_x(ui2_SliderTop, 0);
    lv_obj_set_y(ui2_SliderTop, -43);
    lv_obj_set_align(ui2_SliderTop, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui2_SliderTop, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui2_SliderTop, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui2_SliderTop, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui2_SliderTop, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui2_SliderTop, &ui2_img_display_top_on_png, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui2_SliderTop, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui2_SliderTop, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

}

void ui2_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_basic_init(dispp);
    lv_disp_set_theme(dispp, theme);
    ui2_Screen1_screen_init();
    ui2____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui2_Screen1);
}
