// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.4
// Project name: Right_Display

#include "ui2.h"

void ui2_Screen1_screen_init(void)
{
    ui2_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui2_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_img_src(ui2_Screen1, &ui2_img_display_right_vol_bg_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui2_VolTopSlider = lv_slider_create(ui2_Screen1);
    lv_slider_set_value(ui2_VolTopSlider, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui2_VolTopSlider) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui2_VolTopSlider, 3,
                                                                                                 LV_ANIM_OFF);
    lv_obj_set_width(ui2_VolTopSlider, 284);
    lv_obj_set_height(ui2_VolTopSlider, 30);
    lv_obj_set_x(ui2_VolTopSlider, 4);
    lv_obj_set_y(ui2_VolTopSlider, -30);
    lv_obj_set_align(ui2_VolTopSlider, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui2_VolTopSlider, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui2_VolTopSlider, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui2_VolTopSlider, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui2_VolTopSlider, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui2_VolTopSlider, &ui2_img_display_right_vol_bar_top_png,
                                LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui2_VolTopSlider, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui2_VolTopSlider, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui2_VolBotSlider = lv_slider_create(ui2_Screen1);
    lv_slider_set_value(ui2_VolBotSlider, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui2_VolBotSlider) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui2_VolBotSlider, 0,
                                                                                                 LV_ANIM_OFF);
    lv_obj_set_width(ui2_VolBotSlider, 284);
    lv_obj_set_height(ui2_VolBotSlider, 30);
    lv_obj_set_x(ui2_VolBotSlider, 4);
    lv_obj_set_y(ui2_VolBotSlider, 33);
    lv_obj_set_align(ui2_VolBotSlider, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui2_VolBotSlider, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui2_VolBotSlider, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui2_VolBotSlider, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui2_VolBotSlider, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui2_VolBotSlider, &ui2_img_display_right_vol_bar_bot_png,
                                LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui2_VolBotSlider, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui2_VolBotSlider, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

}
