// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.4
// Project name: Right_Display

#include "ui2.h"

void ui2_Screen3_screen_init(void)
{
    ui2_Screen3 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui2_Screen3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_img_src(ui2_Screen3, &ui2_img_display_right_vu_bg_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui2_Roller2 = lv_roller_create(ui2_Screen3);
    lv_roller_set_options(ui2_Roller2, "Delay Left\nDelay Right\nDelay Sub\nLevel Sub\nInvert Sub\nMirror EQ\nSave", LV_ROLLER_MODE_NORMAL);
    lv_roller_set_selected(ui2_Roller2, 6, false);
    lv_obj_set_height(ui2_Roller2, 119);
    lv_obj_set_width(ui2_Roller2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui2_Roller2, 106);
    lv_obj_set_y(ui2_Roller2, -2);
    lv_obj_set_align(ui2_Roller2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui2_Roller2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE);     /// Flags
    lv_obj_set_style_text_color(ui2_Roller2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui2_Roller2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui2_Roller2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui2_Roller2, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui2_Roller2, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui2_Roller2, lv_color_hex(0x292831), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui2_Roller2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui2_Roller2, lv_color_hex(0x293031), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui2_Roller2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui2_Roller2, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui2_Roller2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui2_Roller2, lv_color_hex(0x2095F6), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui2_Roller2, 255, LV_PART_SELECTED | LV_STATE_DEFAULT);

    ui2_Label1 = lv_label_create(ui2_Screen3);
    lv_obj_set_width(ui2_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui2_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui2_Label1, -45);
    lv_obj_set_y(ui2_Label1, 14);
    lv_obj_set_align(ui2_Label1, LV_ALIGN_CENTER);
    lv_obj_set_style_text_color(ui2_Label1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
    lv_label_set_text(ui2_Label1, "Save");
    lv_obj_set_style_text_font(ui2_Label1, &ui_font_Digitaled, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui2_Label4 = lv_label_create(ui2_Screen3);
    lv_obj_set_width(ui2_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui2_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui2_Label4, -43);
    lv_obj_set_y(ui2_Label4, -33);
    lv_obj_set_align(ui2_Label4, LV_ALIGN_CENTER);
    lv_obj_set_style_text_color(ui2_Label4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
    lv_label_set_text(ui2_Label4, "Configure Settings");
    lv_obj_set_style_text_font(ui2_Label4, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

}
