// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.4
// Project name: Right_Display

#include "ui2.h"

void ui2_Screen2_screen_init(void)
{
    ui2_Screen2 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui2_Screen2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_img_src(ui2_Screen2, &ui2_img_display_right_eq_bg_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui2_EQSlider1 = lv_slider_create(ui2_Screen2);
    lv_slider_set_value(ui2_EQSlider1, 20, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui2_EQSlider1) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui2_EQSlider1, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui2_EQSlider1, 10);
    lv_obj_set_height(ui2_EQSlider1, 105);
    lv_obj_set_x(ui2_EQSlider1, -128);
    lv_obj_set_y(ui2_EQSlider1, 3);
    lv_obj_set_align(ui2_EQSlider1, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui2_EQSlider1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui2_EQSlider1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui2_EQSlider1, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui2_EQSlider1, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui2_EQSlider1, &ui2_img_display_right_eq_bar_png, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui2_EQSlider1, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui2_EQSlider1, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui2_EQSlider2 = lv_slider_create(ui2_Screen2);
    lv_slider_set_value(ui2_EQSlider2, 35, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui2_EQSlider2) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui2_EQSlider2, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui2_EQSlider2, 10);
    lv_obj_set_height(ui2_EQSlider2, 105);
    lv_obj_set_x(ui2_EQSlider2, -110);
    lv_obj_set_y(ui2_EQSlider2, 3);
    lv_obj_set_align(ui2_EQSlider2, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui2_EQSlider2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui2_EQSlider2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui2_EQSlider2, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui2_EQSlider2, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui2_EQSlider2, &ui2_img_display_right_eq_bar_png, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui2_EQSlider2, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui2_EQSlider2, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui2_EQSlider3 = lv_slider_create(ui2_Screen2);
    lv_slider_set_value(ui2_EQSlider3, 45, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui2_EQSlider3) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui2_EQSlider3, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui2_EQSlider3, 10);
    lv_obj_set_height(ui2_EQSlider3, 105);
    lv_obj_set_x(ui2_EQSlider3, -92);
    lv_obj_set_y(ui2_EQSlider3, 3);
    lv_obj_set_align(ui2_EQSlider3, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui2_EQSlider3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui2_EQSlider3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui2_EQSlider3, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui2_EQSlider3, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui2_EQSlider3, &ui2_img_display_right_eq_bar_png, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui2_EQSlider3, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui2_EQSlider3, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui2_EQSlider4 = lv_slider_create(ui2_Screen2);
    lv_slider_set_value(ui2_EQSlider4, 70, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui2_EQSlider4) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui2_EQSlider4, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui2_EQSlider4, 10);
    lv_obj_set_height(ui2_EQSlider4, 105);
    lv_obj_set_x(ui2_EQSlider4, -73);
    lv_obj_set_y(ui2_EQSlider4, 3);
    lv_obj_set_align(ui2_EQSlider4, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui2_EQSlider4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui2_EQSlider4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui2_EQSlider4, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui2_EQSlider4, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui2_EQSlider4, &ui2_img_display_right_eq_bar_png, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui2_EQSlider4, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui2_EQSlider4, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui2_EQSlider5 = lv_slider_create(ui2_Screen2);
    lv_slider_set_value(ui2_EQSlider5, 90, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui2_EQSlider5) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui2_EQSlider5, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui2_EQSlider5, 10);
    lv_obj_set_height(ui2_EQSlider5, 105);
    lv_obj_set_x(ui2_EQSlider5, -55);
    lv_obj_set_y(ui2_EQSlider5, 3);
    lv_obj_set_align(ui2_EQSlider5, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui2_EQSlider5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui2_EQSlider5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui2_EQSlider5, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui2_EQSlider5, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui2_EQSlider5, &ui2_img_display_right_eq_bar_png, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui2_EQSlider5, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui2_EQSlider5, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui2_EQSlider6 = lv_slider_create(ui2_Screen2);
    lv_slider_set_value(ui2_EQSlider6, 100, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui2_EQSlider6) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui2_EQSlider6, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui2_EQSlider6, 10);
    lv_obj_set_height(ui2_EQSlider6, 105);
    lv_obj_set_x(ui2_EQSlider6, -37);
    lv_obj_set_y(ui2_EQSlider6, 3);
    lv_obj_set_align(ui2_EQSlider6, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui2_EQSlider6, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui2_EQSlider6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui2_EQSlider6, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui2_EQSlider6, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui2_EQSlider6, &ui2_img_display_right_eq_bar_png, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui2_EQSlider6, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui2_EQSlider6, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui2_EQSlider7 = lv_slider_create(ui2_Screen2);
    lv_slider_set_value(ui2_EQSlider7, 75, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui2_EQSlider7) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui2_EQSlider7, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui2_EQSlider7, 10);
    lv_obj_set_height(ui2_EQSlider7, 105);
    lv_obj_set_x(ui2_EQSlider7, -19);
    lv_obj_set_y(ui2_EQSlider7, 3);
    lv_obj_set_align(ui2_EQSlider7, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui2_EQSlider7, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui2_EQSlider7, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui2_EQSlider7, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui2_EQSlider7, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui2_EQSlider7, &ui2_img_display_right_eq_bar_png, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui2_EQSlider7, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui2_EQSlider7, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui2_EQSlider8 = lv_slider_create(ui2_Screen2);
    lv_slider_set_value(ui2_EQSlider8, 55, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui2_EQSlider8) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui2_EQSlider8, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui2_EQSlider8, 10);
    lv_obj_set_height(ui2_EQSlider8, 105);
    lv_obj_set_x(ui2_EQSlider8, 19);
    lv_obj_set_y(ui2_EQSlider8, 3);
    lv_obj_set_align(ui2_EQSlider8, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui2_EQSlider8, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui2_EQSlider8, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui2_EQSlider8, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui2_EQSlider8, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui2_EQSlider8, &ui2_img_display_right_eq_bar_png, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui2_EQSlider8, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui2_EQSlider8, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui2_EQSlider9 = lv_slider_create(ui2_Screen2);
    lv_slider_set_value(ui2_EQSlider9, 30, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui2_EQSlider9) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui2_EQSlider9, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui2_EQSlider9, 10);
    lv_obj_set_height(ui2_EQSlider9, 105);
    lv_obj_set_x(ui2_EQSlider9, 37);
    lv_obj_set_y(ui2_EQSlider9, 3);
    lv_obj_set_align(ui2_EQSlider9, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui2_EQSlider9, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui2_EQSlider9, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui2_EQSlider9, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui2_EQSlider9, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui2_EQSlider9, &ui2_img_display_right_eq_bar_png, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui2_EQSlider9, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui2_EQSlider9, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui2_EQSlider10 = lv_slider_create(ui2_Screen2);
    lv_slider_set_value(ui2_EQSlider10, 10, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui2_EQSlider10) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui2_EQSlider10, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui2_EQSlider10, 10);
    lv_obj_set_height(ui2_EQSlider10, 105);
    lv_obj_set_x(ui2_EQSlider10, 55);
    lv_obj_set_y(ui2_EQSlider10, 3);
    lv_obj_set_align(ui2_EQSlider10, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui2_EQSlider10, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui2_EQSlider10, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui2_EQSlider10, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui2_EQSlider10, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui2_EQSlider10, &ui2_img_display_right_eq_bar_png, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui2_EQSlider10, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui2_EQSlider10, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui2_EQSlider11 = lv_slider_create(ui2_Screen2);
    lv_slider_set_value(ui2_EQSlider11, 15, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui2_EQSlider11) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui2_EQSlider11, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui2_EQSlider11, 10);
    lv_obj_set_height(ui2_EQSlider11, 105);
    lv_obj_set_x(ui2_EQSlider11, 74);
    lv_obj_set_y(ui2_EQSlider11, 3);
    lv_obj_set_align(ui2_EQSlider11, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui2_EQSlider11, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui2_EQSlider11, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui2_EQSlider11, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui2_EQSlider11, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui2_EQSlider11, &ui2_img_display_right_eq_bar_png, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui2_EQSlider11, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui2_EQSlider11, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui2_EQSlider12 = lv_slider_create(ui2_Screen2);
    lv_slider_set_value(ui2_EQSlider12, 10, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui2_EQSlider12) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui2_EQSlider12, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui2_EQSlider12, 10);
    lv_obj_set_height(ui2_EQSlider12, 105);
    lv_obj_set_x(ui2_EQSlider12, 92);
    lv_obj_set_y(ui2_EQSlider12, 3);
    lv_obj_set_align(ui2_EQSlider12, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui2_EQSlider12, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui2_EQSlider12, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui2_EQSlider12, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui2_EQSlider12, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui2_EQSlider12, &ui2_img_display_right_eq_bar_png, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui2_EQSlider12, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui2_EQSlider12, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui2_EQSlider13 = lv_slider_create(ui2_Screen2);
    lv_slider_set_value(ui2_EQSlider13, 20, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui2_EQSlider13) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui2_EQSlider13, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui2_EQSlider13, 10);
    lv_obj_set_height(ui2_EQSlider13, 105);
    lv_obj_set_x(ui2_EQSlider13, 110);
    lv_obj_set_y(ui2_EQSlider13, 3);
    lv_obj_set_align(ui2_EQSlider13, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui2_EQSlider13, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui2_EQSlider13, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui2_EQSlider13, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui2_EQSlider13, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui2_EQSlider13, &ui2_img_display_right_eq_bar_png, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui2_EQSlider13, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui2_EQSlider13, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui2_EQSlider14 = lv_slider_create(ui2_Screen2);
    lv_slider_set_value(ui2_EQSlider14, 40, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui2_EQSlider14) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui2_EQSlider14, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui2_EQSlider14, 10);
    lv_obj_set_height(ui2_EQSlider14, 105);
    lv_obj_set_x(ui2_EQSlider14, 128);
    lv_obj_set_y(ui2_EQSlider14, 3);
    lv_obj_set_align(ui2_EQSlider14, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui2_EQSlider14, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui2_EQSlider14, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui2_EQSlider14, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui2_EQSlider14, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui2_EQSlider14, &ui2_img_display_right_eq_bar_png, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui2_EQSlider14, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui2_EQSlider14, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

}
